package pl.pwr.nbaproject.model.api

const val DATA = "data"
const val META = "meta"

const val ID = "id"
const val PLAYER = "player"
const val TEAM = "team"
const val TEAM_ID = "team_id"
const val GAME = "game"

const val ABBREVIATION = "abbreviation"
const val CITY = "city"
const val CONFERENCE = "conference"
const val DIVISION = "division"
const val FULL_NAME = "full_name"
const val NAME = "name"

const val PLAYER_ID = "player_id"
const val GAMES_PLAYED = "games_played"

const val MINUTES = "min"
const val POINTS = "pts"
const val ASSISTS = "ast"
const val REBOUNDS = "reb"
const val DEFENSIVE_REBOUNDS = "dreb"
const val OFFENSIVE_REBOUNDS = "oreb"
const val BLOCKS = "blk"
const val STEALS = "stl"
const val TURNOVER = "turnover"
const val PERSONAL_FOULS = "pf"
const val FIELD_GOALS_ATTEMPTED = "fga"
const val FIELD_GOALS_MADE = "fgm"
const val FIELD_GOAL_PERCENTAGE = "fg_pct"
const val THREE_POINTERS_ATTEMPTED = "fg3a"
const val THREE_POINTERS_MADE = "fg3m"
const val THREE_POINTER_PERCENTAGE = "fg3_pct"
const val FREE_THROWS_ATTEMPTED = "fta"
const val FREE_THROWS_MADE = "ftm"
const val FREE_THROW_PERCENTAGE = "ft_pct"

const val FIRST_NAME = "first_name"
const val LAST_NAME = "last_name"
const val POSITION = "position"
const val HEIGHT_FEET = "height_feet"
const val HEIGHT_INCHES = "height_inches"
const val WEIGHT_POUNDS = "weight_pounds"

const val TOTAL_PAGES = "total_pages"
const val CURRENT_PAGE = "current_page"
const val NEXT_PAGE = "next_page"
const val PER_PAGE = "per_page"
const val TOTAL_COUNT = "total_count"

const val DATE = "date"
const val HOME_TEAM_SCORE = "home_team_score"
const val VISITOR_TEAM_SCORE = "visitor_team_score"
const val SEASON = "season"
const val PERIOD = "period"
const val STATUS = "status"
const val TIME = "time"
const val POSTSEASON = "postseason"
const val HOME_TEAM = "home_team"
const val HOME_TEAM_ID = "home_team_id"
const val VISITOR_TEAM = "visitor_team"
const val VISITOR_TEAM_ID = "visitor_team_id"
